# Generated by Django 4.1 on 2022-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_item_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="discount_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
