# Generated by Django 4.1 on 2022-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_item_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="This is test description for the shown product"
            ),
            preserve_default=False,
        ),
    ]
