# Generated by Django 4.1 on 2022-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
