# Generated by Django 4.1.2 on 2022-11-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_order_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="country",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
